### PR TITLE
Update botao.html

### PR DESCRIPTION
**Pull request by rafahthomaz14**

### CODE REVIEW

**Comment by MilleneSilva** [comment]
#hacktoberfestaccepted

**Comment by lennontaqua2021** [comment]
#hacktoberfestaccepted

**Comment by rafahthomaz14** [comment]
#hacktoberfestaccepted

**Comment by rafahthomaz14** [comment]
#hacktoberfestaccepted

**Comment by rafahthomaz14** [comment]
#hacktoberfestaccepted

**Comment by rafahthomaz14** [comment]
#hacktoberfestaccepted

**Comment by MilleneSilva** [comment]
#hacktoberfestaccepted

**Pull request merged**
